abbr_dict = {
    # vietnam abbreviation
    "": "",
    "btc": "ban tổ chức",
    "clb": "Câu lạc bộ",
    "htx": "Hợp tác xã",
    "nxb": "Nhà xuất bản",
    "ôb": "Ông bà",
    "tp": "Thành phố",
    "tt": "thủ tướng",
    "tư" : "Trung ương",
    "tw": "Trung ương",
    "ubnd": "Ủy ban nhân dân",
    "bch": "Ban Chấp hành",
    "chxhcnvn": "Cộng hòa Xã hội Chủ nghĩa Việt Nam",
    "mtdtgpmnvn": "Mặt trận Dân tộc Giải phóng miền Nam Việt Nam",
    "qđndvn": "Quân đội Nhân dân Việt Nam",
    "vnqdđ": "Việt Nam Quốc dân Đảng",
    "vndcch": "Việt Nam Dân chủ Cộng hòa",
    "lhq": "Liên Hiệp Quốc",
    "thpt": "Trung học phổ thông",
    "thcs": "Trung học cơ sở",
    "tphcm": "Thành phố Hồ Chí Minh",
    "hcm": "Hồ Chí Minh",
    "hđnd": "Hội đồng nhân dân",
    "cnh": "công nghiệp hóa",
    "hđh": "hiện đại hóa",
    "nn&ptnt": 'Nông nghiệp và phát triển nông thôn',
    "cp": "chính phủ",
    "ceo": "xi i âu",
    "đh": "đại học",
    "bhxh": "bảo hiểm xã hội",
    "pv": "phóng viên",
    "hlv": "huấn luyện viên",
    "scandal": "sờ ken đồ",
    "mttq": "mặt trận tổ quốc",

    # english word
    "covid": "cô vít",
    "olympic": "ô lim pích",
    "code": "cốt",

    # english abbreviation
    "usd": "u ét đê",
    "url": "u rờ lờ",
    "qr": "quy a",

    # sign
    "%": "phần trăm",
    "+": "cộng",
    "-": "trừ",
    "*": "nhân",
    "/": "chia",
    "$": "đô la",
    "@": "a còng",

    # unit
    "kg": "ki lô gam",
    "đ": "đồng",

    # english alphabet
    "a": "ây",
    "b": "bi",
    "c": "xi",
    "d": "đi",
    "e": "i",
    "f": "ép",
    "g": "di",
    "h": "ết",
    "i": "ai",
    "j": "dây",
    "k": "cây",
    "l": "eo",
    "m": "em",
    "n": "en",
    "o": "âu",
    "p": "pi",
    "q": "kiu",
    "r": "a",
    "s": "ét",
    "t": "ti",
    "u": "iu",
    "v": "vi",
    "w": "đắp liu",
    "x": "ích",
    "y": "goai",
    "z": "dét",


    # english name
    "indonesia": "in đô nê xi a",
    "afghanistan": "áp ga nít xơ tan",
    "argentina": "ác hen ti na",
    "armenia": "ác mê ni a",
    "australia": "ốt xơ trây li a",
    "austria": "áo",
    "belgium":  "bỉ",
    "brazil": "bờ ra xin",
    "bulgaria": "bun ga ri",
    "campuchia": "cam pu chia",
    "canada": "ca na đa",
    "chad": "sát",
    "chile": "chi lê",
    "cuba": "cu ba",
    "iran": "i ran",
    "iraq": "i rắc",
    "ireland": "ai len",
    "israel": "ít xa ren",
    "italy":  "i ta li a",
    "malaysia": "ma lai xi a",
    "mexico": "mê xi cô",
    "myanmar": "mi an ma",
    "mongolia":"mông cổ",
    "netherlands": "hà lan",
    "norway": "na uy",
    "pakistan": "pa kít xơ tan",
    "bangladesh": "băng la đét",
    "philippines": "phi líp pin",
    "poland": "ba lan",
    "portugal": "bồ đào nha",
    "romania": "ru ma ni",
    "russia": "liên bang nga",
    "singapore": "xin ga po",
    "spain": "tây ban nha",
    "sri-lanka": "sờ ri lan ka",
    "sudan": "xu đăng",
    "sweden": "thụy điển",
    "switzerland": "thụy sĩ",
    "thailand": "thái lan",
    "turkey": "thổ nhĩ kỳ",
    "taiwan": "đài loan",
    "ukraine":   "u cờ rai na",
    "usa": "mỹ",
    "uruguay": "u ru guay",
    "vatican": "va ti căng",
    "vanuatu": "va nu a tu",
    "vietnam":  "việt nam",

}


def check_abbr(str):
    try:
        res_str = abbr_dict[str.lower()]
        return res_str
    except KeyError:
        pass
    return ''


